### ISSUE TITLE
Visual Design Overhaul

### ISSUE THREAD

**Issue by justindoran** [community-table-market/addison-county#36]
We are hoping to overhaul the visual design of the platform. There are several issues related to this overhaul. Some are areas the developers noticed needed attention, others are areas where contributors and testers noted special attention was needed, as such this issue is a clearinghouse for those issues:

## Problem Areas
- [ ] - Restaurant Menu titles (#22)
- [ ] - Home page #24 
- [ ] - Mobile-focused menu layouts (#31)

## Help Wanted
- [ ] - Visually distinct farm menus (#32)
- [ ] - Home/landing page (#28)
- [ ] - Restaurants showcase/list
- [ ] - Farms showcase/list
- [ ] - Individual restaurant storefront
- [ ] - Individual farm storefront
- [ ] - About page/Information about CTM itself
- [ ] - Organization information page

## Waiting to be implemented/tested
- [ ] - Business dashboard
- [ ] - User Account page (#12)
